### ISSUE TITLE
Cadastro de mesas

### ISSUE THREAD

**Issue by GuilhermeInoe** [matheusa1/formula-grill-backend#2]
**Como** Administrador 
**Posso** Cadastrar mesas 
**Para** Disponibilizar para reservas

#Critérios de aceite
- [ ] Cadastrar o código de mesa
- [ ] Cadastrar a quantidade de acentos
- [ ] Disponibilidade

**Comment by matheusa1** [comment]
Middleware não está funcionado, adicionar o seguinte código no src/app.module.ts

![Image](https://github.com/user-attachments/assets/dc164a88-1c0d-405d-a408-8a43d04e4750)

ainda na app.module.ts remover o PrismaService do atributo providers

**Comment by matheusa1** [comment]
No create-mesa.dto.ts adicionar validação isString()

pois ao se enviar um número não está sendo tratado o erro
